### ISSUE TITLE
Subir video:

### ISSUE THREAD

**Issue by Davidag31** [LuisFelipeU38/StoreSight#1]
Como encargado de la tienda, quiero poder cargar un video de mi cámara de seguridad, para que el sistema pueda procesar el video y generar reportes basados en el análisis correspondiente.

**Comment by LuisFelipeU38** [comment]
Criterios de Aceptación:

El sistema debe permitir la carga de videos en formatos comunes.
El usuario debe recibir una confirmación de carga exitosa.
El sistema debe validar que el video cumple con los parámetros necesarios para el procesamiento.
