### ISSUE TITLE
Notificaciones de Procesamiento:

### ISSUE THREAD

**Issue by Davidag31** [LuisFelipeU38/StoreSight#13]
Como encargado de la tienda, quiero recibir notificaciones cuando el procesamiento del video haya finalizado, para que no tenga que estar revisando constantemente si el análisis ha terminado.

**Comment by LuisFelipeU38** [comment]
El sistema debe enviar una notificación al usuario cuando el análisis de video esté completo.
La notificación debe incluir un enlace directo para ver los resultados y reportes generados.
