### ISSUE TITLE
Intefaz Usuario Funcional (NF)

### ISSUE THREAD

**Issue by Davidag31** [LuisFelipeU38/StoreSight#19]
Como usuario del sistema, quiero que la interfaz de usuario sea intuitiva y fácil de usar, para que pueda navegar y realizar tareas sin confusión o la necesidad de una extensa formación.

**Comment by LuisFelipeU38** [comment]
Criterios de Aceptación:

La interfaz debe seguir principios de diseño centrado en el usuario, con una estructura clara y lógica que facilite la navegación.
Los elementos interactivos (botones, menús, formularios) deben estar claramente etiquetados y ser fácilmente identificables.
El diseño visual debe ser consistente en todas las pantallas del sistema, con un uso uniforme de colores, tipografías y estilos.
El usuario debe ser capaz de acceder a las funciones principales del sistema en no más de tres clics desde la pantalla principal.
Debe haber un menú de navegación o barra de herramientas accesible en todas las pantallas, permitiendo al usuario moverse fácilmente entre las diferentes secciones del sistema.
Los enlaces y botones deben ser descriptivos, evitando términos técnicos o ambiguos.
