### ISSUE TITLE
Validación de video: 

### ISSUE THREAD

**Issue by Davidag31** [LuisFelipeU38/StoreSight#2]
Como encargado de la tienda, quiero que el sistema valide si el video cumple con los parámetros para el procesamiento, para que pueda saber si el video es apto para el análisis.

**Comment by LuisFelipeU38** [comment]
Criterios de Aceptación:

El sistema debe analizar el video para verificar su calidad y características técnicas.
El usuario debe recibir un mensaje de error si el video no cumple con los parámetros requeridos.
