### ISSUE TITLE
Implementacion Login/Logout

### ISSUE THREAD

**Issue by Davidag31** [LuisFelipeU38/StoreSight#20]
Como usuario del sistema, quiero poder iniciar sesión (login) y cerrar sesión (logout) de manera segura, para que solo yo pueda acceder a mi cuenta y proteger mi información personal.

**Comment by LuisFelipeU38** [comment]
Criterios de Aceptación:

Inicio de Sesión:

El sistema debe requerir un nombre de usuario y contraseña válidos para iniciar sesión.
El sistema debe validar las credenciales ingresadas y permitir el acceso solo si son correctas.
El usuario debe recibir un mensaje claro en caso de credenciales incorrectas, indicando qué información es incorrecta.
Tras un inicio de sesión exitoso, el sistema debe redirigir al usuario a su panel de control o pantalla principal.

Cierre de Sesión:

El sistema debe permitir al usuario cerrar sesión desde cualquier pantalla mediante un botón o enlace claramente visible.
Al cerrar sesión, el sistema debe terminar la sesión actual y redirigir al usuario a la pantalla de inicio de sesión.
El sistema debe asegurarse de que no quede ninguna información personal del usuario en la sesión posterior al cierre, especialmente en dispositivos compartidos.
