### ISSUE TITLE
Visualización de Zonas de Calor

### ISSUE THREAD

**Issue by Davidag31** [LuisFelipeU38/StoreSight#3]
Como encargado de la tienda, quiero ver un mapa de calor que indique las zonas más frecuentadas en mi tienda, para que  pueda identificar las áreas más y menos visitadas para tomar decisiones sobre la disposición de los estantes.

**Comment by LuisFelipeU38** [comment]
Criterios de Aceptación:

El sistema debe generar un mapa de calor visualmente claro y comprensible.
El mapa de calor debe reflejar las áreas de mayor y menor frecuentación en el video.
El usuario debe poder ver el mapa de calor en una interfaz gráfica sencilla.
