### ISSUE TITLE
Rendimiento del Sistema:  NF

### ISSUE THREAD

**Issue by Davidag31** [LuisFelipeU38/StoreSight#8]
Como usuario del sistema, quiero que el procesamiento del video y la generación de reportes sean rápidos, para que no pierda tiempo esperando resultados.

**Comment by LuisFelipeU38** [comment]
Criterios de Aceptación:

El procesamiento de videos no debe exceder un tiempo razonable.
La generación y visualización de reportes debe ser eficiente y rápida.
El sistema debe ser capaz de manejar múltiples cargas de video simultáneamente sin degradar su rendimiento.
